efault: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: furima_40551_development
  username: cansugimoto  # ここには適切なPostgreSQLユーザーを設定
  password: Mtblanc4809  # ここには適切なパスワードを設定
  host: localhost

test:
  <<: *default
  database: furima_40551_test
  username: cansugimoto  # ここには適切なPostgreSQLユーザーを設定
  password: Mtblanc4809  # ここには適切なパスワードを設定
  host: localhost

production:
  <<: *default
  database: furima_40551_production
  username: furima_40551
  password: <%= ENV["FURIMA_40551_DATABASE_PASSWORD"] %>
  host: localhost