default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: cansugimoto
  password: Mtblanc4809
  host: localhost

development:
  <<: *default
  database: furima_40551_development
  username: cansugimoto  # ここには適切なPostgreSQLユーザーを設定
  password: Mtblanc4809  # ここには適切なパスワードを設定
  host: localhost

test:
  <<: *default
  database: furima_40551_test
  username: cansugimoto  # ここには適切なPostgreSQLユーザーを設定
  password: Mtblanc4809  # ここには適切なパスワードを設定
  host: localhost

production:
  <<: *default
  database: furima_40551_production
  username: cansugimoto
  password: Mtblanc4809
  host: localhost